<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create storyShare a photo or write some_35a569</name>
   <tag></tag>
   <elementGuidId>437dfb24-a330-486d-9184-9898f6bb8bf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mount_0_0_S1']/div/div/div/div[3]/div/div/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.x9f619.x1n2onr6.x1ja2u2z.x78zum5.x1iyjqo2.xs83m0k.xeuugli.xl56j7k.x1qjc9v5.xozqiw3.x1q0g3np.x1iplk16.x1xfsgkm.xqmdsaz.x1mtsufr.x1w9j1nh</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=main</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c9b08510-a220-457b-bae4-e1848a401c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>e8de9f6d-b98d-4022-9208-2c3c99e7a607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x9f619 x1n2onr6 x1ja2u2z x78zum5 x1iyjqo2 xs83m0k xeuugli xl56j7k x1qjc9v5 xozqiw3 x1q0g3np x1iplk16 x1xfsgkm xqmdsaz x1mtsufr x1w9j1nh</value>
      <webElementGuid>88e94645-3e3e-4b2d-b1ee-a939c95946fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create storyShare a photo or write something.Remember PasswordNext time you log in on this browser, just click your profile picture instead of typing a password.OKNot NowOKNot NowCreate a postWhat's on your mind, Thegoodstore?Live videoPhoto/videoFeeling/activityNews Feed postsFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookJUAL BELI MOTOR SECOND KOTA MALANGYuda Hartanto  · rnSopsetdo39ul42amll0lgg09868m1a9g376u5t2im14t3hg8l41mgcfflm  · Shared with Private groupDijualVario techno Th 2011Motor sangat terawat No minus… See moreIDR8,650,000  · BatuVario technoMessagetl5Y3NX.comVario technoIDR8,650,000rnSopsetdo39ul4La ll0lgg098nom1a9g376u5t2em14tahg8rMemgcfflrAll reactions:1 11LikeCommentSendFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebook </value>
      <webElementGuid>87bfeea1-9119-47e5-809b-b459ece8dbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mount_0_0_S1&quot;)/div[1]/div[1]/div[@class=&quot;x9f619 x1n2onr6 x1ja2u2z&quot;]/div[@class=&quot;x9f619 x1n2onr6 x1ja2u2z&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1n2onr6 x1ja2u2z&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1n2onr6 xat3117 xxzkxad&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1t2pt76 x1n2onr6 x1ja2u2z x10cihs4&quot;]/div[@class=&quot;x9f619 x1n2onr6 x1ja2u2z x78zum5 x2lah0s xl56j7k x1qjc9v5 xozqiw3 x1q0g3np x1t2pt76 x17upfok&quot;]/div[@class=&quot;x9f619 x1n2onr6 x1ja2u2z x78zum5 x1r8uery x1iyjqo2 xs83m0k xeuugli x1qughib x1cy8zhl xozqiw3 x1q0g3np xylbxtu x1t2pt76 xornbnt&quot;]/div[@class=&quot;x9f619 x1n2onr6 x1ja2u2z x78zum5 x1iyjqo2 xs83m0k xeuugli xl56j7k x1qjc9v5 xozqiw3 x1q0g3np x1iplk16 x1xfsgkm xqmdsaz x1mtsufr x1w9j1nh&quot;]</value>
      <webElementGuid>71839217-fe96-4ea1-bb07-dee1ee2bcf36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount_0_0_S1']/div/div/div/div[3]/div/div/div/div/div/div[2]</value>
      <webElementGuid>016af7c2-a181-4d70-932d-f6fad2a168c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::div[1]</value>
      <webElementGuid>1eeda3fb-eed0-4bc0-b16e-5924a75eb1f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[1]/following::div[4]</value>
      <webElementGuid>31c84556-f781-4d22-96ec-e88a84a9b950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div[2]</value>
      <webElementGuid>1ef0af2a-988b-4516-bd3d-6245323c2bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Create storyShare a photo or write something.Remember PasswordNext time you log in on this browser, just click your profile picture instead of typing a password.OKNot NowOKNot NowCreate a postWhat&quot; , &quot;'&quot; , &quot;s on your mind, Thegoodstore?Live videoPhoto/videoFeeling/activityNews Feed postsFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookJUAL BELI MOTOR SECOND KOTA MALANGYuda Hartanto  · rnSopsetdo39ul42amll0lgg09868m1a9g376u5t2im14t3hg8l41mgcfflm  · Shared with Private groupDijualVario techno Th 2011Motor sangat terawat No minus… See moreIDR8,650,000  · BatuVario technoMessagetl5Y3NX.comVario technoIDR8,650,000rnSopsetdo39ul4La ll0lgg098nom1a9g376u5t2em14tahg8rMemgcfflrAll reactions:1 11LikeCommentSendFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebook &quot;) or . = concat(&quot;Create storyShare a photo or write something.Remember PasswordNext time you log in on this browser, just click your profile picture instead of typing a password.OKNot NowOKNot NowCreate a postWhat&quot; , &quot;'&quot; , &quot;s on your mind, Thegoodstore?Live videoPhoto/videoFeeling/activityNews Feed postsFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookJUAL BELI MOTOR SECOND KOTA MALANGYuda Hartanto  · rnSopsetdo39ul42amll0lgg09868m1a9g376u5t2im14t3hg8l41mgcfflm  · Shared with Private groupDijualVario techno Th 2011Motor sangat terawat No minus… See moreIDR8,650,000  · BatuVario technoMessagetl5Y3NX.comVario technoIDR8,650,000rnSopsetdo39ul4La ll0lgg098nom1a9g376u5t2em14tahg8rMemgcfflrAll reactions:1 11LikeCommentSendFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebook &quot;))]</value>
      <webElementGuid>30543258-d212-46bb-bd0a-3095087557dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount_0_0_T3']/div/div/div/div[3]/div/div/div/div/div/div[2]</value>
      <webElementGuid>060c740e-7e0b-44ea-998f-25cba3c2aa80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[2]/following::div[4]</value>
      <webElementGuid>f6e420d2-8671-4e4a-b295-f38fd014090b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Create storyShare a photo or write something.Remember PasswordNext time you log in on this browser, just click your profile picture instead of typing a password.OKNot NowOKNot NowCreate a postWhat&quot; , &quot;'&quot; , &quot;s on your mind, Thegoodstore?Live videoPhoto/videoFeeling/activityNews Feed postsFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookINFO KHUSUS LOKER PASURUAN PANDAANDewi Fatimah  · rnsdSeoopt8m9u09231592a1i55cl85atach0652gi489t2g5h559utcllih  · Shared with Private groupBarang kali ada cwek yg butuh kerja aq ada loker dipandaan tpi yg bisa menggendarai motor....bkn asal inbox tanya² tpi gk serius mau kerja....ini butuh yg serius klo minat inboxAll reactions:23 2311LikeCommentSendView more answersRatih SyahfitriKerja apa2h2 hours agoLikeReplyView all 2 repliesWrite an answer…FacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebook &quot;) or . = concat(&quot;Create storyShare a photo or write something.Remember PasswordNext time you log in on this browser, just click your profile picture instead of typing a password.OKNot NowOKNot NowCreate a postWhat&quot; , &quot;'&quot; , &quot;s on your mind, Thegoodstore?Live videoPhoto/videoFeeling/activityNews Feed postsFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookINFO KHUSUS LOKER PASURUAN PANDAANDewi Fatimah  · rnsdSeoopt8m9u09231592a1i55cl85atach0652gi489t2g5h559utcllih  · Shared with Private groupBarang kali ada cwek yg butuh kerja aq ada loker dipandaan tpi yg bisa menggendarai motor....bkn asal inbox tanya² tpi gk serius mau kerja....ini butuh yg serius klo minat inboxAll reactions:23 2311LikeCommentSendView more answersRatih SyahfitriKerja apa2h2 hours agoLikeReplyView all 2 repliesWrite an answer…FacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebook &quot;))]</value>
      <webElementGuid>33bbd088-093c-4f56-be14-e6df0023ed1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount_0_0_K/']/div/div/div/div[3]/div/div/div/div/div/div[2]</value>
      <webElementGuid>793bb8c6-b9e9-422d-9fc9-336b5716e16f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Create storyShare a photo or write something.Remember PasswordNext time you log in on this browser, just click your profile picture instead of typing a password.OKNot NowOKNot NowCreate a postWhat&quot; , &quot;'&quot; , &quot;s on your mind, Thegoodstore?Live videoPhoto/videoFeeling/activityNews Feed postsFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookINFO KHUSUS LOKER PASURUAN PANDAANDewi Fatimah  · pooetrSdsn7cu35ugcu1193u7ih6thma1922cc5cmlclgmh1m2mcl68ca0hc  · Shared with Private groupBarang kali ada cwek yg butuh kerja aq ada loker dipandaan tpi yg bisa menggendarai motor....bkn asal inbox tanya² tpi gk serius mau kerja....ini butuh yg serius klo minat inboxAll reactions:23 2311LikeCommentSendView more answersRatih SyahfitriKerja apa2h2 hours agoLikeReplyView all 2 repliesWrite an answer…FacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebook &quot;) or . = concat(&quot;Create storyShare a photo or write something.Remember PasswordNext time you log in on this browser, just click your profile picture instead of typing a password.OKNot NowOKNot NowCreate a postWhat&quot; , &quot;'&quot; , &quot;s on your mind, Thegoodstore?Live videoPhoto/videoFeeling/activityNews Feed postsFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookINFO KHUSUS LOKER PASURUAN PANDAANDewi Fatimah  · pooetrSdsn7cu35ugcu1193u7ih6thma1922cc5cmlclgmh1m2mcl68ca0hc  · Shared with Private groupBarang kali ada cwek yg butuh kerja aq ada loker dipandaan tpi yg bisa menggendarai motor....bkn asal inbox tanya² tpi gk serius mau kerja....ini butuh yg serius klo minat inboxAll reactions:23 2311LikeCommentSendView more answersRatih SyahfitriKerja apa2h2 hours agoLikeReplyView all 2 repliesWrite an answer…FacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebook &quot;))]</value>
      <webElementGuid>cae6d723-a07a-4f8a-bcb1-4814be697891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount_0_0_PS']/div/div/div/div[3]/div/div/div/div/div/div[2]</value>
      <webElementGuid>498be1a4-dae8-4104-87ff-6b96ec2c1dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Create storyShare a photo or write something.Remember PasswordNext time you log in on this browser, just click your profile picture instead of typing a password.OKNot NowOKNot NowCreate a postWhat&quot; , &quot;'&quot; , &quot;s on your mind, Thegoodstore?Live videoPhoto/videoFeeling/activityNews Feed postsFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookInfo Pekerjaan se-Malang RayaLinda Shopid  · oedoSrsntpf0ug9001fm2g82t66u8hg2laumcflhlc5l9h6697h6m076163c  · Shared with Public groupDicari karyawati untuk jaga di toko nanda gajah mada plasa Masuk jam 09.00 pagi sampai 20.30Ketentuan : niat bekerja ,ulet,rajin,jujur,berapakaian rapi /sopan , umur di bawah 25 tahunInformasi lebih lanjut Bisa wa ke nomer :081358542288/ bisa langsung datang ke toko nanda gajah mada plasa malangTrims ditunggu All reactions:10 102LikeCommentSendShareView more answersBeeLantai berapa.1habout an hour agoLikeReplyShareWrite an answer…FacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebook &quot;) or . = concat(&quot;Create storyShare a photo or write something.Remember PasswordNext time you log in on this browser, just click your profile picture instead of typing a password.OKNot NowOKNot NowCreate a postWhat&quot; , &quot;'&quot; , &quot;s on your mind, Thegoodstore?Live videoPhoto/videoFeeling/activityNews Feed postsFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookInfo Pekerjaan se-Malang RayaLinda Shopid  · oedoSrsntpf0ug9001fm2g82t66u8hg2laumcflhlc5l9h6697h6m076163c  · Shared with Public groupDicari karyawati untuk jaga di toko nanda gajah mada plasa Masuk jam 09.00 pagi sampai 20.30Ketentuan : niat bekerja ,ulet,rajin,jujur,berapakaian rapi /sopan , umur di bawah 25 tahunInformasi lebih lanjut Bisa wa ke nomer :081358542288/ bisa langsung datang ke toko nanda gajah mada plasa malangTrims ditunggu All reactions:10 102LikeCommentSendShareView more answersBeeLantai berapa.1habout an hour agoLikeReplyShareWrite an answer…FacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebook &quot;))]</value>
      <webElementGuid>6b10420c-2bf6-4e71-ab98-ae201a1c56e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount_0_0_W3']/div/div/div/div[3]/div/div/div/div/div/div[2]</value>
      <webElementGuid>8dafb592-af0e-4c97-932e-e629062a951b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Create storyShare a photo or write something.Remember PasswordNext time you log in on this browser, just click your profile picture instead of typing a password.OKNot NowOKNot NowCreate a postWhat&quot; , &quot;'&quot; , &quot;s on your mind, Thegoodstore?Live videoPhoto/videoFeeling/activityNews Feed postsFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookJual Beli HP Malang RayaLapak Guege  · eoSdsrtpnoi7lim7g1ag64250u0u41hlc5luu61cg31mga1c1ga3i20i8l41  · Shared with Public groupredi stockseri terbaru 2024infinix Smart 8 plus 4/128gb… See moreIDR1,249,000  · Malang Kotainfinix Smart 8 plus 4/128 128gb baru garansi resmi bnib malkot tidarMessageKcr763.cominfinix Smart 8 plus 4/128 128gb baru garansi resmi bnib malkot tidarIDR1,249,000eoSdsrtpnoi7rim7g1aa64250u0u41Mec5 uu6reg3noga1cLga3i20i8l41LikeCommentSendShareWrite a public comment…FacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebook &quot;) or . = concat(&quot;Create storyShare a photo or write something.Remember PasswordNext time you log in on this browser, just click your profile picture instead of typing a password.OKNot NowOKNot NowCreate a postWhat&quot; , &quot;'&quot; , &quot;s on your mind, Thegoodstore?Live videoPhoto/videoFeeling/activityNews Feed postsFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookJual Beli HP Malang RayaLapak Guege  · eoSdsrtpnoi7lim7g1ag64250u0u41hlc5luu61cg31mga1c1ga3i20i8l41  · Shared with Public groupredi stockseri terbaru 2024infinix Smart 8 plus 4/128gb… See moreIDR1,249,000  · Malang Kotainfinix Smart 8 plus 4/128 128gb baru garansi resmi bnib malkot tidarMessageKcr763.cominfinix Smart 8 plus 4/128 128gb baru garansi resmi bnib malkot tidarIDR1,249,000eoSdsrtpnoi7rim7g1aa64250u0u41Mec5 uu6reg3noga1cLga3i20i8l41LikeCommentSendShareWrite a public comment…FacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebook &quot;))]</value>
      <webElementGuid>23d473f3-5294-4034-b9dc-4edc9252b005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount_0_0_k2']/div/div/div/div[3]/div/div/div/div/div/div[2]</value>
      <webElementGuid>0fb23409-e6d6-4ddc-9fbe-5eed1293728a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Create storyShare a photo or write something.Remember PasswordNext time you log in on this browser, just click your profile picture instead of typing a password.OKNot NowOKNot NowCreate a postWhat&quot; , &quot;'&quot; , &quot;s on your mind, Thegoodstore?Live videoPhoto/videoFeeling/activityNews Feed postsFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookJUAL BELI MOTOR BEKAS MALANG RAYAArifin Boy Streg  · todpSreson2698aail9tmic8m1092mha20h0500lc54lcth6077mcflgfu1t  · Shared with Private groupJual Isuzu panther tahun 1996 CC 2.5 plat N  malang surat lengkap pajak tertib kondisi tinggal pakai .Mesin Joss tidak ngobos,bodi gembring talang bagus tidak isi,Cat mulus.Interior rapi bersih masih ORI.Audio normal … See more+3IDR55,000,000  · Malang Kabupaten1996 Isuzu amigoMessagescReTBtct5.com1996 Isuzu amigoIDR55,000,000todpSreson2698aail9tMrc8m1092mha20h0e0rlce4actL607nmcflgou tAll reactions:1 1LikeCommentSendWrite a comment…FacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebook &quot;) or . = concat(&quot;Create storyShare a photo or write something.Remember PasswordNext time you log in on this browser, just click your profile picture instead of typing a password.OKNot NowOKNot NowCreate a postWhat&quot; , &quot;'&quot; , &quot;s on your mind, Thegoodstore?Live videoPhoto/videoFeeling/activityNews Feed postsFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookJUAL BELI MOTOR BEKAS MALANG RAYAArifin Boy Streg  · todpSreson2698aail9tmic8m1092mha20h0500lc54lcth6077mcflgfu1t  · Shared with Private groupJual Isuzu panther tahun 1996 CC 2.5 plat N  malang surat lengkap pajak tertib kondisi tinggal pakai .Mesin Joss tidak ngobos,bodi gembring talang bagus tidak isi,Cat mulus.Interior rapi bersih masih ORI.Audio normal … See more+3IDR55,000,000  · Malang Kabupaten1996 Isuzu amigoMessagescReTBtct5.com1996 Isuzu amigoIDR55,000,000todpSreson2698aail9tMrc8m1092mha20h0e0rlce4actL607nmcflgou tAll reactions:1 1LikeCommentSendWrite a comment…FacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebook &quot;))]</value>
      <webElementGuid>ec630393-ef5e-462c-8437-109101fbad94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount_0_0_+R']/div/div/div/div[3]/div/div/div/div/div/div[2]</value>
      <webElementGuid>2194a6d0-86ee-42cf-b89a-55b029ec20d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Create storyShare a photo or write something.Remember PasswordNext time you log in on this browser, just click your profile picture instead of typing a password.OKNot NowOKNot NowCreate a postWhat&quot; , &quot;'&quot; , &quot;s on your mind, Thegoodstore?Live videoPhoto/videoFeeling/activityNews Feed postsFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookJUAL BELI MOTOR BEKAS MALANG RAYAAines Oktavia  · Srdopsnetoum6t3fhtf1mm6i611gllfu64881u1f1m75c3h87mc0a480c6a0  · Shared with Private groupWa -082228478898 loksi sngosari lowokjatiIDR20,500  · Malang KotaCary - 87 ss lngkp n kota mesin SAE +???MessageC9gcdRXnQ8.comCary - 87 ss lngkp n kota mesin SAE +???IDR20,500Srdopsnetoumet frtf1mM6i61ngllfu6re81u1f1ma5c3h87oc0L480c6a0LikeCommentSendWrite a comment…FacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebook &quot;) or . = concat(&quot;Create storyShare a photo or write something.Remember PasswordNext time you log in on this browser, just click your profile picture instead of typing a password.OKNot NowOKNot NowCreate a postWhat&quot; , &quot;'&quot; , &quot;s on your mind, Thegoodstore?Live videoPhoto/videoFeeling/activityNews Feed postsFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookJUAL BELI MOTOR BEKAS MALANG RAYAAines Oktavia  · Srdopsnetoum6t3fhtf1mm6i611gllfu64881u1f1m75c3h87mc0a480c6a0  · Shared with Private groupWa -082228478898 loksi sngosari lowokjatiIDR20,500  · Malang KotaCary - 87 ss lngkp n kota mesin SAE +???MessageC9gcdRXnQ8.comCary - 87 ss lngkp n kota mesin SAE +???IDR20,500Srdopsnetoumet frtf1mM6i61ngllfu6re81u1f1ma5c3h87oc0L480c6a0LikeCommentSendWrite a comment…FacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebookFacebook &quot;))]</value>
      <webElementGuid>dde17330-61f5-4a8a-8dbd-2215720b09e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
