<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Facebook helps you connect and share wi_6fb07b</name>
   <tag></tag>
   <elementGuidId>9210d08d-489b-437c-aaa0-1a1dea2d2686</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._8esk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Facebook helps you connect and share with the people in your life.Log inForgotte&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b6531ca5-76ca-434a-b895-4646d8caf3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_8esk</value>
      <webElementGuid>50ba6a3a-8216-4a11-b7dc-b125207a78d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Facebook helps you connect and share with the people in your life.Log inForgotten password?Create new accountCreate a Page for a celebrity, brand or business.</value>
      <webElementGuid>3c660e7f-4f96-4c23-ae6a-b907bc6723e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[1]/div[@class=&quot;_8esj _95k9 _8esf _8opv _8f3m _8ilg _8icx _8op_ _95ka&quot;]/div[@class=&quot;_8esk&quot;]</value>
      <webElementGuid>3d6a0560-deff-4dc4-aa06-5237435ed64d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div</value>
      <webElementGuid>651f0ae2-bc29-4fcc-ad27-ef2a7ded751c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div</value>
      <webElementGuid>6613a8be-0029-4ba7-8df9-07dc82afab0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Facebook helps you connect and share with the people in your life.Log inForgotten password?Create new accountCreate a Page for a celebrity, brand or business.' or . = 'Facebook helps you connect and share with the people in your life.Log inForgotten password?Create new accountCreate a Page for a celebrity, brand or business.')]</value>
      <webElementGuid>5c03f8a0-cede-482f-bb33-7918eef5d11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div</value>
      <webElementGuid>83626af3-ee30-4a2e-a45b-790e42baa2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div</value>
      <webElementGuid>06467853-8b65-4414-acf7-60f8ebc65dd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
